/**
 * Create Actions.
 * @author andre@orefjard.com (André Orefjärd)
 */

export const actions = {
    INITIALIZE: 'INITIALIZE',
    SET_SEARCH_KEY: 'SET_SEARCH_KEY',
    SYMBOL_SEARCH: 'SYMBOL_SEARCH',
    SET_SEARCH_RESULT_LIST: 'SET_SEARCH_RESULT_LIST',
    RESET_SEARCH_KEY_AND_SEARCH_RESULT: 'RESET_SEARCH_KEY_AND_SEARCH_RESULT',
    SELECT_ITEM: 'SELECT_ITEM',
    SAVE_ITEM: 'SAVE_ITEM',
    SELECT_AND_SAVE_ITEM: 'SELECT_AND_SAVE_ITEM',
    CLEAR_SAVED_HISTORY: 'CLEAR_SAVED_HISTORY',
    SELECT_HISTORY_ITEM: 'SELECT_HISTORY_ITEM',
    CLEAR_SAVED_HISTORY_ITEM: 'CLEAR_SAVED_HISTORY_ITEM'
};
